### ISSUE TITLE
Error when loading checkpoint

### ISSUE THREAD

**Issue by rhyderswen** [Leviathon44/SaveLoadCode#1]
Hello!

Thank you so much for making this library, it looks exactly like what I need! However, whenever I try to load a checkpoint, I get the error `Error running script: Error evaluating expression 'Left(SaveCode, LengthOf(SaveCode)-(LengthOf(GridGInfo)+2))': Argument 'Length' must be greater or equal to zero.`. Do you have any clue how to fix? Thank you!

**Comment by Leviathon44** [comment]
Hello! It's been a while since I took a look at this code, but I think I may have found the issue. 

I'm going to hazard a guess that you aren't using the map for your game. I was so focused on figuring out how to make sure the map got saved that I forgot to account for the use case where the developer didn't even have a map! 

I just uploaded a new version under the Leviathon44-patch-1 branch. Give that a try and let me know if that works for you?

**Comment by rhyderswen** [comment]
Thank you so much for the quick reply! You're completely correct that I'm not using a map for the test room I'm running this in! I am in other parts of the game, though. However, now I'm getting the error `Error running script: Error evaluating expression 'ListItem(KValList,1)': ListItem: index 1 is out of range for this list (1 items, last index is 0)`.

**Comment by Leviathon44** [comment]
Oh dang, another good catch. Again, I think it was a case of me focusing so hard on making it so the text processor {once:} and {notfirst:} firings were saved properly that I again didn't account for the case of a game where the player has no {once:} or {notfirst:} text processor commands to save. 

I just updated the branch with what I _think_ should work (I haven't put together a proper test case to check, but the logic should be sound?) Let me know if that works for you.

**Comment by rhyderswen** [comment]
That seems to be working! The only problem now is that the hyperlink colors and a few other CSS things change, but I'm sure can handle that with the game.AfterLoadCodeScript function. Thank you so much for all the quick fixes! I'll let you know if I find any more!

**Comment by Leviathon44** [comment]
Awesome! I'll go ahead and merge that patch into the main branch and close out this issue. Please let me know if you run into any more issues!
